# Generated by Django 5.0.4 on 2024-04-26 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_name', models.CharField(max_length=20, verbose_name='character name')),
                ('weight', models.IntegerField(verbose_name='weight')),
                ('num_jumps', models.IntegerField(verbose_name='number of jumps')),
                ('max_run_vel', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='maximum run velocity')),
                ('jump_height', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='jump height')),
                ('max_h_air_speed', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='maximum horizontal air speed')),
                ('fastfall_speed', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='fastfall speed')),
                ('has_walljump', models.BooleanField(verbose_name='has walljump')),
                ('franchise', models.CharField(max_length=50)),
                ('backstory', models.CharField(max_length=250)),
            ],
        ),
    ]
