# Generated by Django 5.0.4 on 2024-04-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chars', '0002_character_air_jump_height_character_hop_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='codename',
            field=models.CharField(default='', max_length=20, verbose_name='codename'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='img_url',
            field=models.CharField(default='', max_length=50, verbose_name='Image File URL'),
            preserve_default=False,
        ),
    ]
